"""Machine-readable catalog of public harness commands and their lifecycle contracts."""
from __future__ import annotations

from typing import Any


PUBLIC_COMMANDS: list[dict[str, Any]] = [
    {
        "command": "task draft",
        "read_only": False,
        "valid_states": ["NONE", "READY_FOR_DELIVERY", "DELIVERED"],
        "required_inputs": ["task_id", "outcome"],
        "model_facing": True,
        "description": "Create a new task plan bound to current repository state and architecture contract.",
    },
    {
        "command": "task approve",
        "read_only": False,
        "valid_states": ["AWAITING_DEVELOPER_APPROVAL"],
        "required_inputs": ["task_id", "source", "proof_reference", "enforcement_tier"],
        "model_facing": True,
        "description": "Atomically record explicit developer approval and transition task to IMPLEMENTING.",
    },
    {
        "command": "task begin",
        "read_only": False,
        "valid_states": ["APPROVED", "IMPLEMENTING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Start or confirm execution identity for the task (idempotent no-op for IMPLEMENTING).",
    },
    {
        "command": "task prepare-verification",
        "read_only": False,
        "valid_states": ["IMPLEMENTING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Freeze working changes into immutable delivery manifest and derive verification run policy.",
    },
    {
        "command": "task resume",
        "read_only": False,
        "valid_states": ["VERIFYING", "BLOCKED"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Resume task implementation from VERIFYING or BLOCKED state.",
    },
    {
        "command": "task validate-finding",
        "read_only": False,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id", "finding_id", "status"],
        "model_facing": True,
        "description": "Record validation verdict for a reviewer finding outside plan.json.",
    },
    {
        "command": "task verify",
        "read_only": True,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Execute read-only final verifier checking all required gates, evidence, and approvals.",
    },
    {
        "command": "task complete",
        "read_only": False,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Seal verified task run and transition status to READY_FOR_DELIVERY (SHIP_PENDING).",
    },
    {
        "command": "task deliver",
        "read_only": False,
        "valid_states": ["READY_FOR_DELIVERY", "DELIVERED"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Finalize delivery state after git commit (idempotent no-op for DELIVERED).",
    },
    {
        "command": "task reconcile-delivery",
        "read_only": False,
        "valid_states": ["READY_FOR_DELIVERY", "DELIVERED"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Reconcile delivery state against clean committed git working tree.",
    },
    {
        "command": "task revise",
        "read_only": False,
        "valid_states": ["AWAITING_DEVELOPER_APPROVAL", "APPROVED", "IMPLEMENTING", "VERIFYING", "BLOCKED"],
        "required_inputs": ["task_id", "outcome"],
        "model_facing": True,
        "description": "Revise an active task plan while preserving baseline and archiving history.",
    },
    {
        "command": "task status",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Inspect active or specified task status and query next recommended action.",
    },
    {
        "command": "task checkpoint-phase",
        "read_only": False,
        "valid_states": ["IMPLEMENTING"],
        "required_inputs": ["task_id", "phase_id"],
        "model_facing": True,
        "description": "Validate and checkpoint an active implementation phase before advancing.",
    },
    {
        "command": "task debug-evidence",
        "read_only": False,
        "valid_states": ["IMPLEMENTING"],
        "required_inputs": ["task_id", "kind", "reference"],
        "model_facing": True,
        "description": "Record diagnostic reproduction or debug evidence for a task.",
    },
    {
        "command": "task approve-sensitive",
        "read_only": False,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id", "source", "proof_reference", "enforcement_tier"],
        "model_facing": True,
        "description": "Record explicit developer approval for sensitive surfaces during verification.",
    },
    {
        "command": "task cancel",
        "read_only": False,
        "valid_states": ["AWAITING_DEVELOPER_APPROVAL", "APPROVED", "IMPLEMENTING", "VERIFYING", "BLOCKED", "READY_FOR_DELIVERY"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Cancel an active task and mark plan CANCELLED.",
    },
    {
        "command": "preflight",
        "read_only": True,
        "valid_states": ["IMPLEMENTING", "VERIFYING"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Run deterministic preflight checks (Room schema guard, string parity, fast ktlint).",
    },
    {
        "command": "test",
        "read_only": True,
        "valid_states": ["IMPLEMENTING", "VERIFYING"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Run policy-resolved unit or instrumented tests.",
    },
    {
        "command": "assemble",
        "read_only": False,
        "valid_states": ["IMPLEMENTING", "VERIFYING"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Build application debug artifact via project-configured Gradle assemble task.",
    },
    {
        "command": "review package",
        "read_only": False,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Build immutable review package markdown for required specialist reviewers.",
    },
    {
        "command": "review profile",
        "read_only": True,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Resolve reviewer routing profile, model assignments, and review briefs.",
    },
    {
        "command": "review ingest",
        "read_only": False,
        "valid_states": ["VERIFYING"],
        "required_inputs": ["task_id"],
        "model_facing": True,
        "description": "Ingest and verify specialist reviewer reports and record review evidence.",
    },
    {
        "command": "device install-start",
        "read_only": False,
        "valid_states": ["VERIFYING"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Install and start debug build on resolved Android target device.",
    },
    {
        "command": "graph",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Query Universal Android Code & Architecture Graph for feature or symbol dependencies.",
    },
    {
        "command": "task-context",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": ["file_or_symbol"],
        "model_facing": True,
        "description": "Resolve bounded read-only AST context for a target source file or symbol.",
    },
    {
        "command": "context preview",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Preview rendered project context summary for active repository.",
    },
    {
        "command": "context status",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Inspect cache and freshness status of derived project context.",
    },
    {
        "command": "context note",
        "read_only": False,
        "valid_states": ["ANY"],
        "required_inputs": ["note_text"],
        "model_facing": True,
        "description": "Append architectural note or convention to project notes.",
    },
    {
        "command": "context instruct",
        "read_only": False,
        "valid_states": ["ANY"],
        "required_inputs": ["instruction_text"],
        "model_facing": True,
        "description": "Add scoped developer instruction to developer-instructions.json.",
    },
    {
        "command": "context generate",
        "read_only": False,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Generate derived project context artifacts from repository analysis.",
    },
    {
        "command": "context refresh",
        "read_only": False,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Refresh derived project context cache if stale.",
    },
    {
        "command": "commands",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Output machine-readable catalog of public harness commands as JSON.",
    },
    {
        "command": "doctor",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": False,
        "description": "12-dimension health and environment diagnostic for an Android checkout.",
    },
    {
        "command": "repair",
        "read_only": False,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": False,
        "description": "Deterministic restore of managed harness files from pinned kit.",
    },
    {
        "command": "selftest",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": False,
        "description": "Run the deterministic test suite verifying all harness safety invariants.",
    },
    {
        "command": "version",
        "read_only": True,
        "valid_states": ["ANY"],
        "required_inputs": [],
        "model_facing": True,
        "description": "Print active harness engine release version.",
    },
]


def get_public_commands() -> list[dict[str, Any]]:
    """Return a fresh copy of the machine-readable public commands catalog."""
    return [dict(item) for item in PUBLIC_COMMANDS]
